// <auto-generated />
namespace TimeKeepingAndPayroll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddEID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEID));
        
        string IMigrationMetadata.Id
        {
            get { return "202003280255246_AddEID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
