// <auto-generated />
namespace TimeKeepingAndPayroll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class employeeStartDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeeStartDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004192320302_employeeStartDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
